### PR TITLE
Improve Ukrainian l10n

### PR DESCRIPTION
**Pull request by EGYT5453**
I don't want to make a Transifex account, so I am making a GitHub PR instead. I'm sorry if this creates inconveniences.

### CODE REVIEW

**Comment by divVerent** [comment]
Thank you - I think Transifex can't automatically import from here, but I will try.

**Comment by divVerent** [comment]
Reviewed the translation otherwise - the place names are definitely more correct that way (they match Ukrainian Wikipedia in spelling), and you are correct that Ukrainian does not usually use Title Case Like English Does in Titles. I only have one issue, which probably is an accident, so I'll already go ahead, and merge the rest.

**Comment by divVerent** [comment]
Moved your changes into https://github.com/divVerent/aaaaxy/pull/384. Thank you!

Once automated tests pass, I will merge that - as for the "Additional Programming Libraries & Tools", please respond what you want to do there, then I'll merge.

**Comment by EGYT5453** [comment]
> Additional Programming Libraries & Tools
There should be "Додаткові бібліотеки та інструменти".

**Comment by EGYT5453** [comment]
Hm, some checks have been canceled or have failed.

**Comment by divVerent** [comment]
Thank you, merged that too!

**Comment by EGYT5453** [comment]
I remembered one little mistake I made: I changed the string "Обери-Шлях" ("Pick-a-Path") to "Оберіть шлях" ("Pick a path"). The previous translation, except for the capital "Ш", was actually better, so if you can, please change it to "Обери-шлях" (same string as before, but with lowercase "ш").

**Comment by divVerent** [comment]
No problem, just put the change in. Thanks!

**Comment by EGYT5453** [comment]
There is a problem with the update... I see the changes I made to `game.po`, but I don't see the ones I made to `level.po`

**Comment by divVerent** [comment]
Oh, that is my fault - I hadn't noticed your `level.po` changes in this PR either.

**Comment by divVerent** [comment]
Ah, got fooled by Github not even showing the `level.po` changes in the diff view :(

**Comment by divVerent** [comment]
I am sorry - I am merging these changes in now. Can do another release next week to include those.

Sorry for making it that complicated - sadly just accepting a PR won't work as Transifex would instantly overwrite any changes we do here.

**Comment by divVerent** [comment]
Now that I am reviewing the changes, they are definitely more substantial and I would like to know, do you want to be added to the game's credits for these? If so, how should I spell your name? See the others for how it usually has been done.

**Comment by divVerent** [comment]
Doing some more reviewing:

"Аксіома вибогху" probably should be "Аксіома вибору" (that's what Ukrainian Wikipedia calls it).

**Comment by EGYT5453** [comment]
Well, in the comment it was "Misspell "choise" in a funny way", so I made it sound like someone has troubles pronouncing "r". The "XY" part wasn't intentional!

**Comment by divVerent** [comment]
Great! Keeping that, I like it.

**Comment by divVerent** [comment]
Primarily because I already used Transifex for Xonotic. Otherwise no strong reason - it works, that is all.

**Comment by EGYT5453** [comment]
Credit? Well, `Andrii "EGYT"` will be enough

**Comment by divVerent** [comment]
Thanks! Put it all in, will make another release in the following days, latest next Monday.

**Pull request closed without merging**
